site_name: Smart Contract Weakness Classification (SWC)
site_url: https://swcregistry.io/
site_description: Smart Contract Weakness Classification and Test Cases
site_author: Dominik Muhs

repo_url: https://github.com/SmartContractSecurity/SWC-registry
repo_name: SWC Registry
remote_branch: gh-pages
remote_name: origin

strict: true
docs_dir: entries

nav:
  - Overview: index.md
  - SWC-100: docs/SWC-100.md
  - SWC-101: docs/SWC-101.md
  - SWC-102: docs/SWC-102.md
  - SWC-103: docs/SWC-103.md
  - SWC-104: docs/SWC-104.md
  - SWC-105: docs/SWC-105.md
  - SWC-106: docs/SWC-106.md
  - SWC-107: docs/SWC-107.md
  - SWC-108: docs/SWC-108.md
  - SWC-109: docs/SWC-109.md
  - SWC-110: docs/SWC-110.md
  - SWC-111: docs/SWC-111.md
  - SWC-112: docs/SWC-112.md
  - SWC-113: docs/SWC-113.md
  - SWC-114: docs/SWC-114.md
  - SWC-115: docs/SWC-115.md
  - SWC-116: docs/SWC-116.md
  - SWC-117: docs/SWC-117.md
  - SWC-118: docs/SWC-118.md
  - SWC-119: docs/SWC-119.md
  - SWC-120: docs/SWC-120.md
  - SWC-121: docs/SWC-121.md
  - SWC-122: docs/SWC-122.md
  - SWC-123: docs/SWC-123.md
  - SWC-124: docs/SWC-124.md
  - SWC-125: docs/SWC-125.md
  - SWC-126: docs/SWC-126.md
  - SWC-127: docs/SWC-127.md
  - SWC-128: docs/SWC-128.md
  - SWC-129: docs/SWC-129.md
  - SWC-130: docs/SWC-130.md
  - SWC-131: docs/SWC-131.md
  - SWC-132: docs/SWC-132.md
  - SWC-133: docs/SWC-133.md
  - SWC-134: docs/SWC-134.md
  - SWC-135: docs/SWC-135.md
  - SWC-136: docs/SWC-136.md

theme:
  name: "material"
  language: en

markdown_extensions:
  - pymdownx.superfences
